// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://cjlvcjfuntfbdrrkigwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbHZjamZ1bnRmYmRycmtpZ3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzYyMDIsImV4cCI6MjA1NTgxMjIwMn0.FBSsXa2vVmrv78_XeLWZcpMKMUIeRe0mS9hBO7Cn45Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Injeta o token de sessão custom (x-session-token) em TODA requisição — PostgREST
// (para a RLS via current_session_user_id) e Edge Functions. O token é lido do
// localStorage a cada chamada, então sempre reflete a sessão atual.
const fetchWithSessionToken: typeof fetch = (input, init = {}) => {
  let token: string | null = null;
  try {
    const raw = localStorage.getItem("win_analytics_auth");
    if (raw) token = JSON.parse(raw)?.session_token ?? null;
  } catch {
    token = null;
  }
  const headers = new Headers(init.headers);
  if (token) headers.set("x-session-token", token);
  return fetch(input, { ...init, headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithSessionToken,
  },
});